//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuffApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class contracts
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public decimal Price { get; set; }
        public string Validity { get; set; }
        public string Resp { get; set; }
        public string Org { get; set; }
        public string Date { get; set; }
    }
}
