//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuffApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContractsBaseEntities : DbContext
    {
        private static ContractsBaseEntities _context;
        public ContractsBaseEntities()
            : base("name=ContractsBaseEntities")
        {
        }

        public static ContractsBaseEntities GetContext()
        {
            if (_context == null)
                _context = new ContractsBaseEntities();

            return _context;
        }

        
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contracts> contracts { get; set; }
        public virtual DbSet<transferOfContracts> transferOfContracts { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
